# Generated by Django 6.0.1 on 2026-04-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notes', '0004_departement_specialite_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_niveau', to='gestion_notes.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='gestion_notes.niveau')),
            ],
            options={
                'ordering': ['niveau__nom', 'matiere__nom'],
            },
        ),
        migrations.AddField(
            model_name='niveau',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='niveaux', through='gestion_notes.ProgrammeNiveau', to='gestion_notes.matiere'),
        ),
        migrations.AddConstraint(
            model_name='programmeniveau',
            constraint=models.UniqueConstraint(fields=('niveau', 'matiere'), name='unique_matiere_par_niveau'),
        ),
    ]
